"""empty message

Revision ID: 02b0b7db3f2f
Revises: a53ad141fd15
Create Date: 2023-09-12 15:25:08.636439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02b0b7db3f2f'
down_revision = 'a53ad141fd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesional', schema=None) as batch_op:
        batch_op.drop_constraint('profesional_birth_date_key', type_='unique')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_birth_date_key', type_='unique')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_birth_date_key', ['birth_date'])

    with op.batch_alter_table('profesional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('profesional_birth_date_key', ['birth_date'])

    # ### end Alembic commands ###
