"""empty message

Revision ID: 7a1bb333f6f8
Revises: e4c3d6cb8f53
Create Date: 2023-09-13 02:14:55.337099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1bb333f6f8'
down_revision = 'e4c3d6cb8f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['realization_date'])
        batch_op.create_unique_constraint(None, ['consultation_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
