"""empty message

Revision ID: e307b374cc73
Revises: 241743cdd278
Create Date: 2023-09-22 14:37:35.191604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e307b374cc73'
down_revision = '241743cdd278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_constraint('plan_price_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_foreign_key('plan_price_fkey', 'profesional', ['price'], ['id'])

    # ### end Alembic commands ###
