"""empty message

Revision ID: ef8f5a0e406c
Revises: 8b94881ba255
Create Date: 2023-09-15 20:11:44.255084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef8f5a0e406c'
down_revision = '8b94881ba255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesional', schema=None) as batch_op:
        batch_op.drop_constraint('profesional_birth_date_key', type_='unique')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('profesional_birth_date_key', ['birth_date'])

    # ### end Alembic commands ###
